# Generated by Django 5.1.2 on 2024-10-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='order',
        ),
        migrations.AlterField(
            model_name='reception',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='api.order'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
