# Generated by Django 5.1.2 on 2024-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='Customer_name',
            field=models.CharField(default='Abbas ALi Zada', max_length=255),
            preserve_default=False,
        ),
    ]
