# Generated by Django 5.1.2 on 2024-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reception_order_alter_reception_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='now', max_length=255, verbose_name='Order Name : '),
            preserve_default=False,
        ),
    ]
