# Generated by Django 5.1.2 on 2024-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_user_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='order_name',
            field=models.CharField(max_length=255, verbose_name='Order Name '),
        ),
    ]
