# Generated by Django 5.1.2 on 2024-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reception_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='category',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
